### ISSUE TITLE
Incorrect handling of mail address with Roman numerals

### ISSUE THREAD

**Issue by senysoft** [uprzejmie-donosze/uprzejmiedonosze-backend#31]
Dzień dobry, 

System wpisuję Plac Jana Pawła **Ii** 10 zamiast Plac Jana Pawła **II** 10

**Comment by szn** [comment]
Fixed!

(repozytorium UD znajduje się pod adresem: https://bitbucket.org/uprzejmiedonosze/uprzejmiedonosze/)
