### ISSUE TITLE
Review Open API Schema

### ISSUE THREAD

**Issue by szn** [uprzejmie-donosze/uprzejmiedonosze-backend#8]

**Comment by szn** [comment]
@copalco my comments are:

1. This is not a valid OpenAPI/JSON document. I've removed first three lines and convert it to a Swagger format, but still there are missing $refs, descriptions etc. But I need to say, that I'm not that fluent in different Swagger versions. What kind of editor other than VIM should I use to read it?

2. We do need documentation for all the requests. So far only two are described. This is necessary for @mikaeilorfanian to start his work.

I care more about point (2) than formal correctness described in point (1).

**Comment by mikaeilorfanian** [comment]
The endpoints for user auth will have to be defined by me. I'm doing research on a library that can handle g+ and Facebook.

**Comment by szn** [comment]
ping @copalco
